services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: blog
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - C:\docker-volumes\mysql:/var/lib/mysql

  flask_app:
    build: .
    container_name: flask_app_container
    depends_on:
      - mysql
    ports:
      - "5000:5000"
    environment:
      DB_HOST: mysql
      DB_USER: user
      DB_PASSWORD: userpassword
      DB_NAME: blog
    command: ["python", "app.py"]